name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  GH_USER: ${{ github.actor }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Repo of the week
        uses: matronator/repo-of-the-week@latest
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
